{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(alertmanager_build_info)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table-old",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Notifications sent from $instance",
   "type": "stat",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$__range]))) by (integration)",
     "legendFormat": "{{ integration}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "alertlist",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active alerts in $instance",
   "type": "graph",
   "description": "Number of alerts by state such as `active`, `suppressed` etc.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nf log queries count for $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(alertmanager_nflog_queries_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "Nf log query count"
    },
    {
     "expr": "increase(alertmanager_nflog_query_errors_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "Nf log query errors"
    }
   ]
  },
  {
   "title": "Nf log query duration for $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Nf log query duration"
    }
   ]
  },
  {
   "title": "Nf log snapshot size for $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Nf log snapshot size"
    }
   ]
  },
  {
   "title": "Nf log snapshot duration for $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Nf log snapshot size"
    }
   ]
  },
  {
   "title": "Nf log Go GC time for $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "alertmanager_nflog_gc_duration_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "Cluster joined peers"
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Silences count by state on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Silences query count on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(alertmanager_silences_queries_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "Silecnces query count"
    },
    {
     "expr": "increase(alertmanager_silences_query_errors_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "Silecnces query fails"
    }
   ]
  },
  {
   "title": "Silences query duration on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Silecnces query duration"
    }
   ]
  },
  {
   "title": "Silences snapshot size on $instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences_snapshot_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Silecnces snapshot size"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage/s for $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"alertmanager\"}[5m]) * 100) by (pod)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage for $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  }
 ]
}