{
 "title": "ArgoCD",
 "description": "ArgoCD Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info, server)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" },
   { "name": "log_source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{service=~\"argocd.*\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "App Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{kubernetes_namespace=~\"$namespace\",dest_server=~\"$cluster\", health_status!=\"Healthy\"}) by (health_status)"
    }
   ]
  },
  {
   "title": "App Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"}) by (sync_status)",
     "legendFormat": "{{  .sync_status }}"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Repositories (Helm+Git)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sync Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping, phase)",
     "legendFormat": "{{phase}}: {{$grouping}}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Reconciliation Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval])) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (verb, resource_kind)",
     "legendFormat": "{{verb}} {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Total kubectl run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(argocd_kubectl_exec_total[5m]) ",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Pending kubectl run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"$namespace\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "Controller Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"application-controller\",namespace=~\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\".+application-controller.+\"}[5m])* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", container=\"application-controller\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Resource Objects Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "API Resources Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(argocd_cluster_api_resources{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cluster Events Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_cluster_events_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace, repo)",
     "legendFormat": "{{kubernetes_namespace}} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace, repo)",
     "legendFormat": "{{kubernetes_namespace}} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Fetch Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Git Ls-Remote Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"repo-server\", namespace=~\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=~\"$namespace\", pod=~\".+repo-server.+\"}[5m])* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", container=\"repo-server\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"server\", namespace=~\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", container=\"server\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"server\", quantile=\"1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 161 }, "options": { "content": "#### gRPC Services:" } },
  {
   "title": "ApplicationService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\", grpc_service=\"application.ApplicationService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ClusterService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\", grpc_service=\"cluster.ClusterService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ProjectService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\",grpc_service=\"project.ProjectService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "RepositoryService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\", grpc_service=\"repository.RepositoryService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SessionService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\", grpc_service=\"session.SessionService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "VersionService Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\",grpc_service=\"version.VersionService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "AccountService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\",grpc_service=\"account.AccountService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SettingsService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_handled_total{namespace=~\"$namespace\", grpc_service=\"cluster.SettingsService\"}[$interval])) by (grpc_code, grpc_method))",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  { "title": "Redis Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "title": "Requests by result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\"}[$interval])) by (failed)"
    }
   ]
  },
  {
   "title": "OutOfSync (Loki)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "{namespace=\"argo-cd\"} |=\"OutOfSync\" | logfmt | line_format \"{{ .time }}\\t{{ .reason }}  {{ printf \\\"%-20.20s\\\" .application }}\\t{{ .msg }}\\t{{ .dest_server }}\""
    }
   ]
  }
 ]
}