{
 "title": "Generic Service Metrics",
 "description": "Simplifies monitoring services on Kubernetes. Shows container logs, availability, resource usage and HTTP traffic.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"argo-cd|prod|staging|grafana|prometheus\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "loglevel",
    "label": "Log level",
    "query": "label_values({namespace=\"$namespace\", container=\"$service\"}, level)"
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Average uptime of the service in the selected time range",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  min(ceil(\n    kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"$service|.*$service.*\"} /\n    kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\"$service|.*$service.*\"}\n  ))\n[$__range:1m])"
    },
    {
     "expr": "avg_over_time(\n  min(ceil(\n    kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=~\"$service|.*$service.*\"} /\n    kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=~\"$service|.*$service.*\"}\n  ))\n[$__range:1m])"
    }
   ]
  },
  {
   "title": "Replicas healthy",
   "type": "state-timeline",
   "description": "Timeline showing when how many of the desired replicas were healthy",
   "gridPos": { "h": 5, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"$service|.*$service.*\"} /\n  kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\"$service|.*$service.*\"}\n) by (deployment)",
     "legendFormat": " "
    },
    {
     "expr": "max(\n  kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=~\"$service|.*$service.*\"} /\n  kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=~\"$service|.*$service.*\"}\n) by (statefulset)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Timeline showing when pod restarts occurred",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=~\".*$service.*\"}[5m])) * 300 > 0"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "description": "Running versions (Docker image tags) over time.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(label_replace(kube_pod_container_info{namespace=\"$namespace\",container=\"$service\"}, \"version\", \"$1\", \"image\", \".*:(.*)\")) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage of the main container (without sidecars)",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$service\"}) by (pod) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the main container (without sidecars)",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$service\"}[$__rate_interval])) by (pod) != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Response times",
   "type": "heatmap",
   "description": "Distribution of response times as measured by ingress controller",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_response_duration_seconds_bucket{namespace=\"$namespace\",service=~\"$service|.*$service.*\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum(increase(istio_request_duration_milliseconds_bucket{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "description": "Request count by HTTP status code as measured by ingress controller",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=\"$namespace\",service=~\"$service|.*$service.*\"}[$__rate_interval])) by (method, status)",
     "legendFormat": "{{method}}: {{status}}"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\"}[$__rate_interval])) by (response_code)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Logs reported by the main container (without sidecars)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=\"$service\", level=~\"$loglevel\"}"
    }
   ]
  },
  { "title": "HTTP Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "The time of the probe connection (like API or external/internal services over HTTP(s) protocol)",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{service=\"$service\"}) by (component,$service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certs Validity",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}