{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "description": "Alerts",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ALERTS)", "legendFormat": "Active Alerts" }
   ]
  },
  {
   "title": "NotReady Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"}>0)"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Crashing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(kube_pod_container_status_restarts_total{job=\"kubernetes-service-endpoints\"}[5m]) * 60 * 5 > 0)"
    }
   ]
  },
  {
   "title": "Pod Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum by (status) (count_over_time({job=\"ingress-nginx/ingress-nginx\"} | json | status=~\"4.*|5.*\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "EKS Cluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes{}) * 100",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_namespace=~\"ingress-nginx\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "EKS Cluster CPU Usage (5m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum (machine_cpu_cores{})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) by (instance) / sum (machine_cpu_cores) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ingress Upstream Response Time",
   "type": "graph",
   "description": "The time spent on receiving the response from the upstream server",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n      }[2m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_response_duration_seconds_bucket{\n      }[2m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_response_duration_seconds_bucket{\n      }[2m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "EKS Cluster Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Ingress Request Handling Time",
   "type": "graph",
   "description": "Total time taken for nginx and upstream servers to process a request and send a response",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{}[2m]\n    )\n  )\n)",
     "legendFormat": ".5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n    nginx_ingress_controller_request_duration_seconds_bucket{}[2m]\n    )\n  )\n)",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n      }[2m]\n    )\n  )\n)",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "filters": "severity=critical" }
   ]
  },
  {
   "title": "Alerts last 3 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    { "expr": "SUM(ALERTS)" }
   ]
  }
 ]
}