{
 "title": "MongoDB Instances Compare",
 "tags": [
  "MongoDB_Compare",
  "Percona"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mongodb_up{instance=~\"$instance\"}, node_name)"
   },
   {
    "name": "instance",
    "label": "Service Name",
    "query": "label_values(mongodb_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Opened Cursors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mongodb_mongod_metrics_cursor_open{instance=~\"$instance\"} or mongodb_mongod_cursors{instance=~\"$instance\"} or mongodb_mongos_metrics_cursor_open{instance=~\"$instance\"} or mongodb_mongos_cursors{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Replica Set",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=~\"$instance\"}",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Service Info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "repeat": "service_name",
   "targets": [
    {
     "expr": "mongodb_version_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "MongoDB Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mongodb_instance_uptime_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (max_over_time(mongodb_connections{instance=~\"$instance\",state=\"current\"}[$interval]) or max_over_time(mongodb_connections{instance=~\"$instance\",state=\"current\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_op_counters_total{instance=~\"$instance\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{instance=~\"$instance\",type!=\"command\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (rate(mongodb_mongod_op_latencies_latency_total{instance=~\"$instance\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{instance=~\"$instance\",type=\"command\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{instance=~\"$instance\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{instance=~\"$instance\",type=\"command\"}[5m]) > 0))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "ReplSet State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,state) (max_over_time(mongodb_mongod_connections{instance=~\"$instance\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongod_connections{instance=~\"$instance\", state=~\"current|available\"}[5m]) or max_over_time(mongodb_mongos_connections{instance=~\"$instance\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongos_connections{instance=~\"$instance\", state=~\"current|available\"}[5m]) or \nmax_over_time(mongodb_connections{instance=~\"$instance\", state=~\"current|available\"}[$interval]) or \nmax_over_time(mongodb_connections{instance=~\"$instance\", state=~\"current|available\"}[5m]))",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cursors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,state) (mongodb_mongod_metrics_cursor_open{instance=~\"$instance\"} or \nmongodb_mongod_cursors{instance=~\"$instance\"} or \nmongodb_mongos_metrics_cursor_open{instance=~\"$instance\"} or \nmongodb_mongos_cursors{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,type) (rate(mongodb_mongod_op_latencies_latency_total{instance=~\"$instance\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{instance=~\"$instance\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{instance=~\"$instance\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{instance=~\"$instance\"}[5m]) > 0))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Scan Ratios",
   "type": "graph",
   "description": "Ratio of index entries scanned or whole docs scanned / number of documents returned",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=\"scanned\"}[$interval]) / ignoring(state) rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\", state=\"returned\"}[$interval]) or (irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=\"scanned\"}[5m]) / ignoring(state) irate(mongodb_mongod_metrics_document_total{instance=~\"$instance\", state=\"returned\"}[5m])))",
     "legendFormat": "Index {{instance}}"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\", state=\"returned\"}[$interval]) / ignoring(state)rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=\"scanned_objects\"}[$interval]) or\nirate(mongodb_mongod_metrics_document_total{instance=~\"$instance\", state=\"returned\"}[5m]) / ignoring(state)irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=\"scanned_objects\"}[5m]))",
     "legendFormat": "Document {{instance}}"
    }
   ]
  },
  {
   "title": "Index Filtering Effectiveness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (instance) (mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=~\"scanned_objects\"}) / ignoring(state)sum by (instance) (mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\", state=~\"scanned_objects|scanned\"})",
     "legendFormat": "{{instance}} - Index"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Ops/sec (classified by (legacy) wire protocol request type)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,type) (rate(mongodb_mongod_op_counters_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$instance\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$instance\"}[5m]) or \nrate(mongodb_op_counters_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_op_counters_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "description": "Documents inserted/updated/deleted or returned per sec",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,state) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[5m]))\n",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "The number of operations that are currently queued and waiting for a lock",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,type) (max_over_time(mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"}[$interval]) or max_over_time(mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,type) (max_over_time(mongodb_memory{instance=~\"$instance\"}[$interval]) or\nmax_over_time(mongodb_memory{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  }
 ]
}