{
 "title": "Kubernetes - Cluster Overview",
 "description": "Overview of Kubernetes cluster-level metrics",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_version",
    "query": "label_values(kube_node_info, kubelet_version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "content": "<div class=\"text-center\">\n  <img style=\"height:80px\" src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1200px-Kubernetes_logo_without_workmark.svg.png\">\n  <h2 style=\"padding-top:15px\">$k8s_version</h2>\n</div>",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",image!=\"\"})/sum(machine_memory_bytes)*100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",image!=\"\"}[5m]))/sum(machine_cpu_cores)*100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})/sum(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})*100"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable==0)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable!=0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "cores",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",image!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "cores",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Daemon Sets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_unavailable)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_daemonset_status_number_available)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_created) - count(kube_deployment_status_replicas_available)",
     "legendFormat": "Failed"
    },
    { "expr": "count(kube_deployment_created)", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Pods",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running|Succeeded\"}) OR on() vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Replica Sets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_replicaset_created) - count(kube_replicaset_status_ready_replicas)",
     "legendFormat": "Failed"
    },
    { "expr": "count(kube_replicaset_created)", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Stateful Sets",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_statefulset_created) - count(kube_statefulset_status_replicas_ready)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(kube_statefulset_created)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace!=\"\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}