{
 "title": "Kubernetes Event Exporter",
 "description": "Kubernetes Event Exporter - https://github.com/resmoio/kubernetes-event-exporter",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "contains", "label": "Search events" }
  ]
 },
 "panels": [
  { "title": "Kubernetes Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=\"event-exporter\"} |~ \"(?i)$contains\" | json | __error__=\"\" | namespace_extracted=~\"$namespace\""
    }
   ]
  },
  { "title": "Kubernetes Events - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | type=\"Warning\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"Error: ImagePullBackOff\" | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"Failed\"  | line_format \"{{ .message }}\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Probe Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"failed liveness probe\" | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"Killing\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Volume Mount Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"FailedMount\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Scheduling Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"FailedScheduling\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"OOMKilling\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"BackOff\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} |= \"Marking for deletion Pod\" | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"TaintManagerEviction\" [$__interval]))"
    }
   ]
  },
  {
   "title": "System OOM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" | reason=\"SystemOOM\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Kubernetes Events - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events by Reason",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (reason) (count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" [$__interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Events by Namespace",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (namespace_extracted) (count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" [$__interval]))",
       "legendFormat": "{{namespace_extracted}}"
      }
     ]
    },
    {
     "title": "Events by Source",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (component_extracted) (count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" [$__interval]))",
       "legendFormat": "{{component_extracted}}"
      }
     ]
    },
    {
     "title": "Events by Kind",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by (kind) (count_over_time({container=\"event-exporter\"} | json | __error__=\"\" | namespace_extracted=~\"$namespace\" [$__interval]))",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Events - Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{container=\"event-exporter\"} |~ \"(?i)$contains\" | json | __error__=\"\" | namespace_extracted=~\"$namespace\""
      }
     ]
    }
   ]
  }
 ]
}